### ISSUE TITLE
Implement "Kudos Milestone" label

### ISSUE THREAD

**Issue by ipapandinas** [kudos-ink/portal#87]
## Overview

Introduce a "kudos-milestone" label to spotlight key tracking issues open for contributions, fostering a broader engagement with external contributors. This label aims to outline a larger vision and offer incentives upon the completion of these milestones. Each tracking issue may encompass sub-tasks to provide a structured approach to achieving these milestones.

## How

- [ ] Integrate a new column in the Notion database to link each issue with a "Milestones Tracking Issue" ID
- [ ] Add a "Milestones" section on project pages to display Kudos Milestones tracking issues, visualized as a multi-step roadmap
- [ ] Create a dedicated "milestone" page
- [ ] Support dynamic slugs in the format "milestone/TITLE-for-PROJECT"
- [ ] The "milestone" page features a table for issues belonging to this specific milestone. The issues are filtered by milestone ID and the table contains columns for Status, Title, Assignee, and Date.
- [ ] Add a "Latest Kudos Milestones" section on the homepage for increased visibility
